services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - 1443:1443
    env_file:
      - .env
  
  wordpress:
    build:
      conext: ./requirements/wordpress
    env_file:
      - .env
