services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - 1443:1443
    volumes:
      - WordPress:/etc/wordpressvolume
    env_file:
      - .env
  
  wordpress:
    build:
      context: ./requirements/wordpress
    volumes:
      - WordPress:/etc/wordpressvolume
    env_file:
      - .env


volumes:
  WordPress:
    name: WordPress
  DB:
    name: DB